
name: Compile Unreal Plugin

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-plugin:
    name: Build Plugin
    runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix:
        ue-version: [5.1, 5.2, 5.3, 5.4, 5.5]
        configuration: [Development, Shipping]
        
    env:
      UE_PATH: "C:\\Program Files\\Epic Games\\"
      PLUGIN_NAME: "MaskTools"
      PLATFORM: "Win64"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Plugin for ${{ matrix.ue-version }} - ${{ matrix.configuration }}
        shell: powershell
        run: '&"${{ env.UE_PATH }}${{ matrix.ue-version }}\Engine\Build\BatchFiles\RunUAT.bat" BuildPlugin -Plugin="${{ github.workspace }}\${{ env.PLUGIN_NAME }}.uplugin" -Package="${{ github.workspace }}\PackagedPlugins\${{ env.PLUGIN_NAME }}" -TargetPlatforms=${{ env.PLATFORM }} -Configuration=${{ matrix.configuration }}'

      - name: Upload Built Plugin
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PLUGIN_NAME }}-Built
          path: ${{ github.workspace }}/PackagedPlugins/${{ env.PLUGIN_NAME }}
